pipeline {
	agent { label 'master' } 
	stages {
		stage('Both build and test') {
			parallel {
				stage('Build') { 
					steps {
						sh 'sleep 15; echo "This is a Build stage"'
					}
				}
				
				stage('Test'){
					steps {
						sh '''
							sleep 15
							echo "This is a Test stage"
						'''	
						git branch: 'main', url: 'https://github.com/jaintpharsha/devops-jan-22.git'
					}
				}
			} 
		}
		stage('Deploy'){
			steps {
				sh '''
					sleep 5
					echo "This is a Deploy stage"
				'''
			}
		}
		
		stage('My-stage'){
			steps {
				sh '''
					sleep 5
					echo "This is a My-stage stage"
				'''
			}
		}	
	}
}